# Site settings
title: The Or!
email: fmabroad@gmail.com
phone: +841213866888
description: > # this means to ignore newlines until "baseurl:"
  Blog thiết kế & phát triển website sáng tạo, tạo cảm hứng, bằng tiếng Việt Nam, của người Việt Nam.
url: "http://oriiiii.com" # the base hostname & protocol for your site
author: Huy Pham
twitter_username: envyInside
github_username: f-ma

# Plugins

# Conversion
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Markdown Processors
kramdown:
  input: GFM
